development:
  adapter: async

test:
  adapter: test

production:
  adapter: async

  # url: redis://localhost:6379
  # adapter: redis
  # channel_prefix: bigwave_api_production

 # adapter: redis
 # url: redis://redis.api.ibigwave.com:6379
